default_platform(:ios)

require "json"

import "./functions/lanes/Fastfile_iosArchive.rb"
import "./functions/lanes/YKConfigScriptEnv.rb"
import "./functions/Fastfile_workfaild.rb"

before_all do |lane, options|
  fast_file_path = File.expand_path(File.dirname(__FILE__))

  options[:fast_file_path] = fast_file_path
  options[:first_lane] = lane

  # 路径类参数,在此处变为绝对路径
  @script_run_path = options[:script_run_path].blank? ? File.expand_path(Dir.pwd) : options[:script_run_path]
  options[:script_run_path] = @script_run_path

  puts "script_run_path:#{@script_run_path}"
  Dir.chdir(@script_run_path) do
    options[:xcworkspace] = options[:xcworkspace].blank? ? @script_run_path : File.expand_path(options[:xcworkspace])
    options[:flutter_directory] = options[:flutter_directory].blank? ? "" : File.expand_path(options[:flutter_directory])
  end
end

error do |lane, exception, options|
  UI.import("error:#{exception}")
  clear_build_temp
  workfaild_yk(lane, exception, options)
end

